directive @Authenticated on FIELD | FIELD_DEFINITION
directive @Account(type: ACCOUNT_TYPE ,permissions: [PERMISSION]) on FIELD | FIELD_DEFINITION


enum ACCOUNT_TYPE{
  ADMIN
  USER
  CUSTOMER
}

enum PERMISSION{
  STORE
  STAFF
}