type Permission{
  _id: String
  name: String
  description: String
}

input CreatePermissionInput{
  name: String!
  description: String
}

input UpdatePermissionInput{
  _id: String!
  name: String!
  description: String
}

input DeletePermissionInput{
  ids: [String]
}

type Query{
  permissions: [Permission] @Authenticated
}

type Mutation{
  createPermission(input: CreatePermissionInput): Permission @Authenticated @Account(type: ADMIN)
  updatePermission(input: UpdatePermissionInput): Permission @Authenticated @Account(type: ADMIN)
  deletePermission(input: DeletePermissionInput): Boolean @Authenticated @Account(type: ADMIN)
}