type Permission{
  _id: String
  name: String
  description: String
}

input CreatePermissionInput{
  name: String!
  description: String
}

input UpdatePermissionInput{
  _id: String!
  name: String!
  description: String
}

input DeletePermissionInput{
  ids: [String]
}

type Query{
  permissions: [Permission] @Auth
}

type Mutation{
  createPermission(input: CreatePermissionInput): Permission @Auth @Has(type: ADMIN)
  updatePermission(input: UpdatePermissionInput): Permission @Auth @Has(type: ADMIN)
  deletePermission(input: DeletePermissionInput): Boolean @Auth @Has(type: ADMIN)
}