type Permission{
  _id: String
  name: String
  description: String
}

input CreatePermissionInput{
  name: String!
  description: String
}

input UpdatePermissionInput{
  _id: String!
  name: String!
  description: String
}

input DeletePermissionInput{
  ids: [String]
}

type Query{
  permissions: [Permission] @isAuth
}

type Mutation{
  createPermission(input: CreatePermissionInput): Permission @isAuth @hasType(type: "ADMIN")
  updatePermission(input: UpdatePermissionInput): Permission @isAuth @hasType(type: "ADMIN")
  deletePermission(input: DeletePermissionInput): Boolean @isAuth @hasType(type: "ADMIN")
}