type Admin{
  _id: String
  email: String
  fullname: String
}

input CreateAdminInput{
  email: String!
  fullname: String
}

input UpdateAdminInput{
  _id: String!
  email: String!
  fullname: String
}

input AdminLoginInput{
  email: String!
  password: String!
}

input DeleteAdminInput{
  ids: [String]
}

type Query{
  admins: [Admin] @Auth @Account(type: ADMIN)
  currentAdmin: Admin @Auth @Account(type: ADMIN)
}

type Mutation{
  loginAdmin(input: AdminLoginInput): String!

  createAdmin(input: CreateAdminInput): Admin @Auth @Account(type: ADMIN)
  updateAdmin(input: UpdateAdminInput): Admin @Auth @Account(type: ADMIN)
  deleteAdmin(input: DeleteAdminInput): Boolean @Auth @Account(type: ADMIN)
}