type Admin{
  _id: String
  email: String
  fullname: String
}

input CreateAdminInput{
  email: String!
  fullname: String
}

input UpdateAdminInput{
  _id: String!
  email: String!
  fullname: String
}

input AdminLoginInput{
  email: String!
  password: String!
}

input DeleteAdminInput{
  ids: [String]
}

type Query{
  admins: [Admin] @Authenticated @Account(type: ADMIN)
  currentAdmin: Admin @Authenticated @Account(type: ADMIN)
}

type Mutation{
  adminLogin(input: AdminLoginInput): String!

  createAdmin(input: CreateAdminInput): Admin @Authenticated @Account(type: ADMIN)
  updateAdmin(input: UpdateAdminInput): Admin @Authenticated @Account(type: ADMIN)
  deleteAdmin(input: DeleteAdminInput): Boolean @Authenticated @Account(type: ADMIN)
}