type Role{
  _id: String
  shop: Shop
  user: User
  permissions: [Permission]
  name: String
  isMaster: Boolean
  description: String
}

type Query{
  staffs(idShop: String): [Role] @Staff(with: "STAFF")
}

type Mutation{
  createRole(idShop: String, input: CreateRoleInput): Role @Staff(with: "STAFF")
  updateRole(idShop: String, input: UpdateRoleInput): Role @Staff(with: "STAFF")
  deleteRole(idShop: String, id: String): Boolean @Staff(with: "STAFF")
}

input CreateRoleInput{
  idUser: String
  idPermissions: [String]
  name: String
  description: String
}

input UpdateRoleInput{
  _id: String
  idPermissions: [String]
  name: String
  description: String
}