type Plan{
  _id: String
  name: String
  duration: Int
  price: Float
  state: PlanState
  description: String
  createdAt: Float
}

enum PlanState{
  DRAFT
  PUBLISHED
  SUPPRESSED
}

type Query{
  plans: [Plan] @Admin
  publishedPlans: [Plan]
}

type Mutation{
  createDraftPlan(input: CreateDraftPlanInput): Plan @Admin
  updateDraftPlan(input: UpdateDraftPlanInput): Plan @Admin
  deleteDraftPlan(ids: [String]): Boolean @Admin
  publishPlan(id: String): Plan @Admin
  suppressPlan(id: String): Plan @Admin
}

input CreateDraftPlanInput{
  name: String
  duration: Int
  price: Float
  description: String
}

input UpdateDraftPlanInput{
  _id: String
  name: String
  duration: Int
  price: Float
  description: String
}