type Profile{
  dob: Float
  fullName: String
  address: String
  phone: String
  avatar: String
}

input UpdateProfileInput{
  dob: Float
  fullName: String
  address: String
  phone: String
  avatar: String
}

type Mutation {
  updateUserProfile(input: UpdateProfileInput): Profile @Auth
}