type User{
  _id: String
  isAdmin: Boolean
  profile: Profile
  credential: Credential
}

type Query{
  users: [User] @Auth @Admin
  currentUser: User @Auth 
}

type Mutation{
  loginUser(input: LoginInput): String!
  
  changeUserPassword(input: ChangePasswordInput): String @Auth 

  createUser(input: CreateUserInput): User @Auth @Admin
  updateAdmin(input: UpdateAdminInput): User @Auth @Admin
  deleteUser(input: DeleteUserInput): Boolean @Auth @Admin
}

input CreateUserInput{
  email: String
  fullName: String
  isAdmin: Boolean
}

input DeleteUserInput{
  ids: [String]
}

input UpdateAdminInput{
  _id: String
  isAdmin: Boolean
}
