type User{
  _id: String
  isAdmin: Boolean
  profile: Profile
  credential: Credential
}

type Query{
  users: [User] @Auth
  currentUser: User @Auth 
}

type Mutation{
  loginUser(input: LoginInput): String!
  changeUserPassword(input: ChangePasswordInput): String @Auth 

  createUser(input: CreateUserInput): User @Auth
  deleteUser(input: DeleteUserInput): Boolean @Auth 
}

input CreateUserInput{
  email: String
  fullName: String
  isAdmin: Boolean
}

input DeleteUserInput{
  ids: [String]
}
