type Category{
  _id: String
  name: String
  parent: Category
}

type Query{
  categories(idShop: String): [Category] @Staff(with: "PRODUCT")
}

type Mutation{
  createCategory(idShop: String, input: CreateCategoryInput): Category @Staff(with: "PRODUCT")
  updateCategory(idShop: String, input: UpdateCategoryInput): Category @Staff(with: "PRODUCT")
  deleteCategory(idShop: String, id: String): Boolean @Staff(with: "PRODUCT")
}

input CreateCategoryInput{
  idParent: String
  name: String
}

input UpdateCategoryInput{
  _id: String
  name: String
}
